[application]

# App (Project) Name
name = "loom"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

[web.app]

# HTML title tag content
title = "loom"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# include `assets` in web platform
[web.resource]

# CSS style file
#style = ["/tailwind.css"]


# Javascript code file
# "https://cdn.tailwindcss.com/3.4.5"
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[serve]
port = 8080
addr = "0.0.0.0"

[bundle]
identifier = "com.navilalabs"
publisher = "NavilaLabs UG (haftungsbeschränkt)"
icon = ["assets/favicon.svg"]
